Lint/HandleExceptions:
  Enabled: false
Lint/Eval:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/ClassAndModuleCamelCase:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FileName:
  Exclude:
    - bin/ffi-yajl-bench
Style/HashSyntax:
  EnforcedStyle: 'ruby19'
